---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.4/manifests/install.yaml
  - addons.yaml
  - httproute.yaml

patches:
  - path: ./patches/argocd-cm.yaml
  - path: ./patches/argocd-repo-server.yaml

generators:
  - ./secret-generator.yaml
